# Config file for automatic testing at travis-ci.org

sudo: false
language: python
# https://docs.travis-ci.com/user/caching/#before_cache-phase
#cache:
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
#python:
#  - "3.5"
#  - "nightly"

matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27
      - python: 3.3
        env: TOX_ENV=py33
      - python: 3.4
        env: TOX_ENV=py34
      - python: 3.5
        env: TOX_ENV=py35
      - python: nightly
        env: TOX_ENV=py36
      - python: pypy
        env: TOX_ENV=pypy

before_script:
  - "export aaa=`which python3.6`"
  - "echo $aaa"
  - python -c "import sys; print(sys.version)"

script:
  - "export aaa=`which python3.6`"
  - "echo $aaa"
  - python -c "import sys; print(sys.version)"
  - tox -e $TOX_ENV
