# Config file for automatic testing at travis-ci.org

sudo: false
language: python
# https://docs.travis-ci.com/user/caching/#before_cache-phase
#cache:
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
#python:
#  - "3.5"
#  - "nightly"


#env:
#    - TOX_ENV=py34
#    - TOX_ENV=py35
#    - TOX_ENV=py36

matrix:
    include:
      - python: 3.5
        env: TOX_ENV=py34
      - python: 3.5
        env: TOX_ENV=py35
      - python: nightly
        env: TOX_ENV=py36
#    exclude:
#      - python: nightly
#        env: TOX_ENV=py34
#      - python: nightly
#        env: TOX_ENV=py35
#      - python: 3.5
#        env: TOX_ENV=py36

before_script:
  - "export aaa=`which python3.6`"
  - "echo $aaa"
  - python -c "import sys; print(sys.version)"

script:
  - "export aaa=`which python3.6`"
  - "echo $aaa"
  - python -c "import sys; print(sys.version)"
  - tox -e $TOX_ENV
