# Config file for automatic testing at travis-ci.org


sudo: false
language: python
# https://docs.travis-ci.com/user/caching/#before_cache-phase
#cache:
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
#python:
#  - "3.5"
#  - "nightly"

matrix:
    include:
      - os: linux
        python: 2.7
        env: TOX_ENV=py27
      - os: linux
        python: 3.3
        env: TOX_ENV=py33
      - os: linux
        python: 3.4
        env: TOX_ENV=py34
      - os: linux
        python: 3.5
        env: TOX_ENV=py35
      - os: linux
        python: nightly
        env: TOX_ENV=py36
      - os: linux
        python: pypy
        env: TOX_ENV=pypy
      - os: osx
        language: generic
        osx_image: xcode7.2
        env: TOX_ENV=py35
    allow_failures:
      - os: linux
        python: nightly
        env: TOX_ENV=py36

before_script:
  - "echo 'available python:'"
  - python -c "import sys; print(sys.version)"
  - "whereis python"
install:
    - ./.travis/install.sh
script:
  - "export aaa=`which python3.6`"
  - "echo $aaa"
  - python -c "import sys; print(sys.version)"
  - tox -e $TOX_ENV
