# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ativo', models.NullBooleanField(default=True, editable=False)),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_assinatura_assinado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssinaturaBloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('esta_ativo', models.NullBooleanField(default=True)),
                ('assinantes', models.ManyToManyField(blank=True, related_name='assinaturas', through='core.Assinatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('documento',),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_hash', models.UUIDField(editable=False, null=True, unique=True)),
                ('status_assinatura', models.PositiveSmallIntegerField(choices=[(10, 'Não Assinado'), (20, 'Possui Assinaturas Pendentes'), (30, 'Esta assinado e não possui nenhuma assinatura pendente')], default=10)),
            ],
        ),
        migrations.AddField(
            model_name='assinaturabloco',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloco_assinatura', to='core.Documento'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='assinatura_bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='core.AssinaturaBloco'),
        ),
    ]
