# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='uuid_hash',
            field=models.UUIDField(db_index=True, editable=False, null=True, unique=True),
        ),
    ]
