# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160524_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='esta_assinado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='assinaturabloco',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_bloco_assinatura', to='core.Documento'),
        ),
    ]
