# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160601_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinaturabloco',
            old_name='datahora',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='documento',
            name='assinatura_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='conteudo_documento',
            field=models.TextField(blank=True),
        ),
    ]
